### ISSUE TITLE
Create a custom Error enum to be used by the API

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe-cli#131]
A custom Error struct is required to be used in the API which will allow us to have a clean set of error codes, as well as adding localisation support in the future.

**Comment by calumcraig** [comment]
Moving this to done as there aren't any changes in functionality to test. https://maidsafe.slack.com/archives/CHJ1HPV29/p1563368748245100?thread_ts=1563361423.243900&cid=CHJ1HPV29
