### ISSUE TITLE
Setup mock-network tests

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe-cli#141]
With #85 integrated for files / data. We should be able to get the `mock-network` tests to run, at least at the integration level.
(the vault is painfully slow, so I'd say a full test suite run is out of scope for now).

**Comment by joshuef** [comment]
Marked as blocked until https://github.com/maidsafe/safe-cli/pull/144/commits/61a33029ec14aad974060e901d1d608d64c83020#diff-be3a3da11bd849af346eda3fe6d22ac5R404

has been resolved. 

@lionel1704 mentioned they may be switching to simply providing a the key rather than an option here, which would alleviate this error. (And prevent the need for us to be defining out own `CoreError` as `run` accepts.

**Comment by calumcraig** [comment]
Testing on `wallet` and `nrs` commands this week (as well as utilising associated `files` commands` has been done on safe-cli binaries built using `cargo build features=mock-network`. No issues related to using this mock network have been encountered.

[Confirmed with devs](https://maidsafe.slack.com/archives/CHJ1HPV29/p1564743693401200) that QA other than this is not really applicable for this issue.

Moving to done.
