### ISSUE TITLE
Fetch API: support decoding NRS-URLs and fetching NRS Containers

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe-cli#149]
We need the `fetch` API to decode NRS-URLs if they are detected to not be XOR-URLs, and retrieve the corresponding content by fetching the NRS Container using the decoded public name, subname, and paths.

**Comment by calumcraig** [comment]
[Confirmed with developers](https://maidsafe.slack.com/archives/CHJ1HPV29/p1565006515419200?thread_ts=1565006374.419000&cid=CHJ1HPV29) that this issue does not require any additional QA to testing that has already been done for other issues. The `safe cat safe://nrsurl` functionality was tested for issue #148 

Moving this to done.
