### ISSUE TITLE
Minor refactor in XOR-URLs encoder to have separate bytes for content type and SAFE data type

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe-cli#150]
We need to include information about the native data type a content is being stored on, as well as the content type of the data being stored, this is required to give applications the ability to act accordingly to both fetch the data from the network using the corresponding client API (depending on the native data type, e.g. Published/Unpublished ImmD, Published/Unpublished AppendOnlyData, sequenced/unsequenced, etc.), and parse/interpret the content of the data being retrieved according to the content type (e.g. FilesContainer RDF, Wallet RDF, etc.).

We need to store this information in two separate bytes encoded in the XOR-URL.

**Comment by calumcraig** [comment]
[Confirmed with developers](https://maidsafe.slack.com/archives/CHJ1HPV29/p1565006536419400?thread_ts=1565006374.419000&cid=CHJ1HPV29) that no additional QA work needs done on this issue - extensive testing has been done elsewhere and no issues (related to this one) have been uncovered.

**Comment by calumcraig** [comment]
Moving this to done.
