### ISSUE TITLE
Support for NRS URLs across all API and CLI commands

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe-cli#177]
Up until now, all commands and API were using XOR-URLs for locating content, we shall support both type of URLs across existing API and CLI, i.e. both NRS and XOR URLs can be provided by the user when providing the location of any type of content (we shall eventually also support HEX encoded XoR names).

**Comment by calumcraig** [comment]
Testing on this binary: `safe-cli.s3.amazonaws.com/safe_cli-15cfd1a-x86_64-unknown-linux-gnu.tar`

**Comment by calumcraig** [comment]
Tested the following functions using nrsurls in place of xorurls:
1) keys balance
2) wallet balance
3) wallet insert
4) wallet transfer
5) files sync
6) cat
7) nrs create
8) nrs add
9) nrs remove

**Comment by calumcraig** [comment]
Attaching test notes here rather than inserting as comments.
[safe-cli__nrs_test_notes.txt](https://github.com/maidsafe/safe-cli/files/3482112/safe-cli__nrs_test_notes.txt)

**Comment by calumcraig** [comment]
QA verified, moving this to done.
