### ISSUE TITLE
Option to define default file for NRS?

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe-cli#179]
Resolving to a filescontainer... but which file to render if browser?

This info should probably go in the NRS map, alongside the default entry, default file perhaps?

**Comment by JimCollinson** [comment]
Couple of quick thoughts...

- Defaults to `index` in the first instance or `home`, unless a file has been specified.
- If neither of the above a present, and a file has not been specified perhaps it is just based on the first file uploaded.
- Or perhaps after that, if say the files were added at the same time, it is simple based on the first alphabetically?

**Comment by bochaco** [comment]
@joshuef  @JimCollinson I don't think this is part of NRS, this is something from the application consuming that content, in this case a browser, in clearnet DNS doesn't do this but the web server, so in our case this can perhaps be part of the `webFetch` API which BTW I think we are missing from this current plan (https://github.com/maidsafe/safe-cli/projects/6). So I propose we fix/implement this issue by implementing the missing `webFetch` function which internally uses the `fetch` and returns an object with info similar to an HTTP response, just like we do in safe-app-nodejs for alpha2

**Comment by joshuef** [comment]
Hmmmm...  if you wanted many behaviours by many different apps, you'd need to specify that... So maybe you're right. Maybe we can set a default by having an RDF file within the container, that the app (browser in this case) knows to look for.

**Comment by bochaco** [comment]
Yes, depending on the app consuming the content a default can be totally different things, and conceptually it's not NRS responsibility.
For the FilesContainer it makes sense to me, I think we had even considered this before, currently in alpha2 the default filename is hardcoded in the lib which is obviously incorrect, what if the consuming app is a photo gallery app? the default then is one of the pictures and not an index.html

**Comment by joshuef** [comment]
Yeh cool. I'm sold on that. Closing this and we can work such a thing into the NRS RFC as a note for application implementations.

**Comment by calumcraig** [comment]
This has been closed as `wontfix` and won't involve any development. Therefore QA in not applicable to this particular issue and I will move this to done.
