### ISSUE TITLE
safe keys create with no arguments throws an error

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safe-cli#192]
[Issues related to this have previously been tested and fixed](https://github.com/maidsafe/safe-cli/issues/42), so this appears to be a regression.

Steps to reproduce:
`safe keys create` with no arguments

Expected:
```
safe_cli keys create
Enter secret key corresponding to public key at XOR-URL "Missing the 'source' argument":
```
Actual:
```
> ./safe keys create
[2019-08-06T10:31:20Z ERROR safe] safe_cli error: [Error] Unexpected - Unexpected error when attempting to create Key: [Error] NetDataError - Failed to create a CoinBalance: "NoSuchBalance"
```

**Comment by bochaco** [comment]
@calumcraig this doesn't fail in v0.1.0 just released, when no args is provided it uses the default SafeKey from the account to pay the costs with. So unless you think there is something still to be fixed we can close this one I believe.

**Comment by calumcraig** [comment]
As @bochaco mentions above, the described action no longer results in a failure:
```
> ./safe keys create
New SafeKey created at: "safe://hbyyyybpoirhe4h6t6pu49bn4ms9t8jexkhk4o4cwspe7z67w98ftq1iqq"
Key pair generated:
pk = b6152711ae7a3e6cf5f08b4bb7e274a1eae2b50d32966a3b7f769f3962e955ce3dccdd6fe0c80fa9e0bf14bfd42ac3b4
sk = 2cc0d69fd24306d47d2e1d87ee2efabfdf8500935e6979a85efd3ec4c1080452
```

**Comment by calumcraig** [comment]
Moving this to done.
