### ISSUE TITLE
Implementation of internal API for MutableData container

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe-cli#22]
We need our API for MD which provides us with the abstractions will need to our CLI use cases, e.g. creating a wallet which contains the links to Keys and their secret keys, eventually we'll expose a set of commands for the user to also create/update and delete an MD form the CLI.

**Comment by joshuef** [comment]
- [x] Create a mutable data
- [ ] Update a mutable data (key/value)
- [ ] Delete a mutable data (key)
