### ISSUE TITLE
`GLIBC_2.25' not found

### ISSUE THREAD

**Issue by dan-da** [maidsafe/safe-cli#286]
I get this error:
```
$ ./safe
./safe: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by ./safe)
```
OS is ubuntu 16.04.1 LTS

**Comment by bochaco** [comment]
hey @dan-da , I'm afraid we may not be supporting v16 of Ubuntu, we've been working only on v18 and v19, is it possible for you to upgrade?

**Comment by dan-da** [comment]
fair enough I guess especially since 16.04 reached end of life in April.  I will see about upgrading.
