### ISSUE TITLE
keys command handling errors

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safe-cli#30]
Testing against `330478c (HEAD -> master, origin/master, origin/HEAD) refactor(lib): changing xor_url var names to xorurl`

**Comment by calumcraig** [comment]
`keys balance` with no XOR-URL

Expected:
Error message will prompt user to input an XOR-URL and return to command prompt.
Actual:
CLI is stuck looking for an XOR-URL and user has to cancel using `CTRL + C`:
```
$ cargo run keys balance
    Finished dev [unoptimized + debuginfo] target(s) in 0.14s
     Running `target/debug/safe_cli keys balance`
Reading target XOR-URL from STDIN...
```

**Comment by calumcraig** [comment]
`keys balance` with a string that is not a valid XOR-URL.

**Expected:**
Error message will prompt user to input a valid XOR-URL and return to command prompt.
**Actual:**
An error is thrown:
```
$ cargo run keys balance safe://bbkulcbe7yufu2z37irvd43nyc2zygergjgpmrkdecd44cpruwhx3a63gkjfvhkerh
    Finished dev [unoptimized + debuginfo] target(s) in 0.15s
     Running `target/debug/safe_cli keys balance 'safe://bbkulcbe7yufu2z37irvd43nyc2zygergjgpmrkdecd44cpruwhx3a63gkjfvhkerh'`
thread 'main' panicked at '

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!   unwrap! called on Result::Err                                              !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
src/lib_helpers.rs:112,15 in safe_cli::lib_helpers

Err(ParsingError)

', /home/calum/.cargo/registry/src/github.com-1ecc6299db9ec823/unwrap-1.2.1/src/lib.rs:67:25
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by calumcraig** [comment]
`keys create` with no argument(s)

**Expected:**
Error message will prompt user to provide valid argument(s).
**Actual:**
There is some feedback about the argument but the error is not handled well:
```
$ cargo run keys create
    Finished dev [unoptimized + debuginfo] target(s) in 0.14s
     Running `target/debug/safe_cli keys create`
thread 'main' panicked at 'Missing the 'from' argument', src/libcore/option.rs:1034:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by bochaco** [comment]
@calumcraig , the first issue about `keys balance` with no XOR-URL, what you see "Reading target XOR-URL from STDIN..." is the CLI waiting for some input stream in the stdin, so if you paste/enter a XOR-URL it will read it and work just fine.

This is how we plan to support piping commands e.g. echo `safe://<xor url> | safe_cli keys balance` will take read XOR_URL from the stdin and get the balance of it.

So I guess we need to enhance the message there, any suggestions?

**Comment by bochaco** [comment]
In PR #29 I'm fixing these three issues; I replaced the message "Reading target XOR-URL from STDIN..." with "...awaiting target XOR-URL from STDIN stream..." but let me know if you can think of some better alternative.

**Comment by calumcraig** [comment]
OK, thanks @bochaco - the fact that the program was awaiting input wasn't obvious to me. You are right though, I can paste an XOR-URl and it works fine.

One observation I would make is that the console doesn't look (to me as a user) that I actually can paste something in there>> 
![image](https://user-images.githubusercontent.com/44327924/59257818-96544480-8c2e-11e9-9038-3b2c9d867ce7.png)

If this function (pasting an OXR-URL as opposed to piping in STDIN) is something that we anticipate being used much do we want to make it clearer that it is possible? Add something to the message and / or make the input point more obvious?

**Comment by bochaco** [comment]
I think we should eventually try to make it that when rading from stdin it fail immediately if there is no input already, so it works only when piping commands but it fails when there is no input stream right when the command is executed. For cases when we want the user to enter something we will be always putting a message like "Please enter....:"

**Comment by calumcraig** [comment]
That sounds like a good solution @bochaco

**Comment by calumcraig** [comment]
The second scenario https://github.com/maidsafe/safe-cli/issues/30#issuecomment-499933873 is still an issue so have raised a new bug to cover that. #41

**Comment by calumcraig** [comment]
The thread panic in the [third scenario](https://github.com/maidsafe/safe-cli/issues/30#issuecomment-500349184) has been fixed but there are new related issues. I'll raise a new bug and move this issue to done.

**Comment by calumcraig** [comment]
The thread panic in the [third scenario](https://github.com/maidsafe/safe-cli/issues/30#issuecomment-500349184) has been fixed but there are new related issues. I'll raise a new bug and move this issue to done.
