### ISSUE TITLE
wallet insert: insert functions seems to work when <key> argument is not supplied

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safe-cli#36]
Steps to reproduce:
1.
```
safe_cli keys create --test-coins --preload 12345`
safe://bbkulcbawons6eox6jrj3vmmizh6qdazqamsypiovnwznjf24wkc2co4tk
pk=82ce6cbc475fc98a775631193fa030660064b0f43aadb65a92eb9650b427726a5a1a6243c2088478ce038404b394130f
sk=b103e3ef6d95b0d21b58709b071cb3169143c0ec57d8d85a6293cc08e4b11626
```
2.
```
safe_cli wallet create --pretty`
Wallet created at XOR-URL: "safe://bbkulcb5xenunqqegww7uojpefxsrdavn3ubhy4yebpxbfwrq5jirhhjh7"
```
3.
```
safe_cli wallet insert 'safe://bbkulcbawons6eox6jrj3vmmizh6qdazqamsypiovnwznjf24wkc2co4tk' 'safe://bbkulcb5xenunqqegww7uojpefxsrdavn3ubhy4yebpxbfwrq5jirhhjh7'`
```

**Expected:**
`<key` argument has not been supplied - some feedback regarding this and user returned to CLI prompt (TBC expected behaviour @joshuef @bochaco ).

**Actual:**
User is prompted to enter the `sk` for the source XOR-URL:
```
Enter secret key corresponding to public key at XOR-URL "safe://bbkulcbawons6eox6jrj3vmmizh6qdazqamsypiovnwznjf24wkc2co4tk": b103e3ef6d95b0d21b58709b071cb3169143c0ec57d8d85a6293cc08e4b11626
```
Doing so triggers some work:
```
safe://bbkulcbgqbas3o4awpffrd2dehcvqx27f4o34wfeu3eaagamn2kbgpnkpi
pk=9a0104b6ee02cf29623d0c8715617d7cbc76f962929b20006031ba504cf6a9e8207cb37bf7bdf56b1edb970af9198046
sk=b6b5bc960ce912d3f313a6c3338c5844676d0876c1ec83cab414810f8b265258
safe://bbkulcb5xenunqqegww7uojpefxsrdavn3ubhy4yebpxbfwrq5jirhhjh7
```
but then when we check the original wallet's balance nothing has been inserted:
```
safe_cli wallet balance 'safe://bbkulcb5xenunqqegww7uojpefxsrdavn3ubhy4yebpxbfwrq5jirhhjh7'`
0
```

**Comment by joshuef** [comment]
The `key` portion is optional. If not supplied a new key is generated and added.

I think this requires a doc update:

eg.
`An existing key safe://xor-url to add to the wallet. If this is not supplied a new key will be generated and inserted.`

**Comment by calumcraig** [comment]
The readme document has been updated as described above:

![image](https://user-images.githubusercontent.com/44327924/59366604-78700800-8d32-11e9-8f20-3affa29dba1c.png)

Moving this to done.
