### ISSUE TITLE
Windows: need to set HOME env var before safe_cli will run

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safe-cli#38]
On Windows attempt to authorise the `safe_cli` application with `safe_cli.exe auth`

**Expected:**
safe_cli will request authorisation.
**Actual:**
Command does not work and an error is returned:
`[2019-06-11T15:10:29Z ERROR safe_cli] safe_cli error: Couldn't find HOME env var: environment variable not found`
Workaround:
`set HOME=<PathToUsersHome>`

**Comment by bochaco** [comment]
I'll be working on this, it seems we just need to use https://crates.io/crates/dirs instead of using `HOME` env var name directly.

**Comment by calumcraig** [comment]
Testing against `0d4e010 (HEAD -> master, origin/master, origin/HEAD) fix(auth): resolve the user home directory using 'dirs' crate`

No errors are returned when the application is used, there is no need for the user to set the HOME env var:

![image](https://user-images.githubusercontent.com/44327924/59351411-4355bc80-8d16-11e9-88f0-7c1acf3c47fb.png)

Moving this to done.
