### ISSUE TITLE
keys create + no arguments related issues

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safe-cli#42]
Previously the command `keys create` without any arguments was [throwing an error](https://github.com/maidsafe/safe-cli/issues/30#issuecomment-500349184) related to a thread panicking.

This issue has been resolved but it has unearthed new related issues.

`safe_cli keys create`
With no arguments not triggers a prompt for user input:
`Enter secret key corresponding to public key at XOR-URL "Missing the 'source' argument":`
The issues detailed here relate to this and what data is input at this point.

**Comment by calumcraig** [comment]
1) no data, user hits `Enter` at the prompt:

```
safe_cli keys create`
Enter secret key corresponding to public key at XOR-URL "Missing the 'source' argument": 
[2019-06-12T14:58:00Z ERROR safe_cli] safe_cli error: Invalid input, expected secret key string
```

**Comment by calumcraig** [comment]
2) User enters invalid string at the prompt:

```
safe_cli keys create`
Enter secret key corresponding to public key at XOR-URL "Missing the 'source' argument": vejvjkrhvkev
[2019-06-12T14:59:11Z ERROR safe_cli] safe_cli error: Failed to decode XOR-URL: ParsingError
```

**Comment by calumcraig** [comment]
3) User enters valid secret key at the prompt:

```
safe_cli keys create`
Enter secret key corresponding to public key at XOR-URL "Missing the 'source' argument": d41f2c2446dd61852c557e7cf04226e06b3a1a393fcb5485fe74603fc3fd2726
[2019-06-12T15:07:38Z ERROR safe_cli] safe_cli error: Failed to decode XOR-URL: ParsingError
```

**Comment by calumcraig** [comment]
4) User enters a valid XOR-URL at the prompt:

```
safe_cli keys create`
Enter secret key corresponding to public key at XOR-URL "Missing the 'source' argument": safe://bbkulcbdvmfaml44757qtn6wmou2go27k4s74fddowhoyjakmzl3y5tekc
[2019-06-12T15:09:47Z ERROR safe_cli] safe_cli error: Failed to decode XOR-URL: ParsingError
```

**Comment by calumcraig** [comment]
Confirmed with @bochaco that the argument passed to `keys create` should be an XOR-URL.

For comparison this is `keys create <validxorurl`:

```
safe_cli keys create 'safe://bbkulcbdvmfaml44757qtn6wmou2go27k4s74fddowhoyjakmzl3y5tekc'`
Enter secret key corresponding to public key at XOR-URL "safe://bbkulcbdvmfaml44757qtn6wmou2go27k4s74fddowhoyjakmzl3y5tekc": d41f2c2446dd61852c557e7cf04226e06b3a1a393fcb5485fe74603fc3fd2726
safe://bbkulcbfxq75g6jamlxczcpvdfyw4fvvr4643wbnstbw26esqjm65qjbu4
pk=96f0ff4de4818bb8b227d465c5b85ad63cf73760b6530db5e24a0967bb04869c26ccf4791dbfcdb681357ed1a9a786ce
sk=bce1cace0af5d657e9a0d907716039a6bf30e7a8576d3c5668de78d925bce83f
```
Ie, the cli takes the xorurl and requests the associated `sk` and in turn creates a new key.

**Comment by calumcraig** [comment]
Analysing above:
1) Prompt for `sk` is missing the xorurl (as it has not been provided):
`Enter secret key corresponding to public key at XOR-URL "Missing the 'source' argument": `
2) Scenario 1 seems valid - user has indeed not provided the secret key string.
3) Scenario 2 - error message is valid (as user has not entered a valid string) but reference is to xorurl while prompt was for secret key.
4) Scenario 3- error message is valid (as user has not entered a valid xorurl) but error itself seems invalid as user has provided what was asked for (secret key).
5) Scenario 4 - error message is invalid (as user has entered a valid xorurl) but error itself seems valid as user has not provided what what was asked for (secret key).

**Comment by bochaco** [comment]
I fixed this with PR #44 , it shouldn't prompt the user for any data if the 'source' is not provided, it should just fail with an error. Either a 'source' or '--test-coins' need to be provided to create a Key.

**Comment by calumcraig** [comment]
Testing against: `safe_cli keys create`
[2019-06-13T08:23:26Z ERROR safe_cli] safe_cli error: Missing the 'source' argument`

When no argument is provided, an error is thrown and the user is advised to that end:
```
safe_cli keys create`
[2019-06-13T08:23:26Z ERROR safe_cli] safe_cli error: Missing the 'source' argument
```
When a `source` argument is provided but it is not a valid xorurl the operation asks for the `sk` but then fails with a different error:
```
safe_cli keys create gverioghogrv`
Enter secret key corresponding to public key at XOR-URL "gverioghogrv": jhjvrhwevk
[2019-06-13T08:26:51Z ERROR safe_cli] safe_cli error: Failed to decode XOR-URL: ParsingError
```

**Comment by calumcraig** [comment]
When a valid xor-url is provided as the `source` argument, user is prompted for the corresponding `sk` (as above):
```
safe_cli keys create 'safe://bbkulcbglfop3wumrpf2ktpalmoqrwwpvxus5gvjn54ctigmj2wpv72g7d'`
Enter secret key corresponding to public key at XOR-URL "safe://bbkulcbglfop3wumrpf2ktpalmoqrwwpvxus5gvjn54ctigmj2wpv72g7d"
```
If a valid `sk` is given a new key is created successfully:
```
a87f60e3461abe6532ef674bd8309a57848928095932bf9a6ea5fec82e82f818
safe://bbkulcbfntu6ph3gws22cgriprhcfs4r7fribmvwd7fepes6yqzt4higod
pk=95b3a79e7d9ad2d68468a1f1388b2e47e58a02cad87f291e497b10ccf87419c31a76f8a8a9a9e28729887667880243b9
sk=94c1a104864eb1ae2d51bd6deabdd56a35de66c24785dee722e6cf49fdf5373e
```
If an invalid `sk` is given the operation fails with feedback:
```
vhwuhwihuidrvbr
[2019-06-13T08:46:47Z ERROR safe_cli] safe_cli error: Failed to deserialize provided secret key
```

**Comment by calumcraig** [comment]
Closing this and moving to done.
