### ISSUE TITLE
Cat cmd: support fetching Published ImmutableData

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe-cli#55]
Simply fetch the content of a Published-ImmutableData given its XOR-URL and printout the content on the stdout, e.g.:
```
$ safe cat safe://<Published-Immd XOR-URL>
hello world
```

**Comment by calumcraig** [comment]
QA verified - `safe cat` successfully retrieves the contents of a file previously uploaded to (mock) network:

```
safe-cli/to-upload$ cat content.txt 
This is a test to create a text file with some content to work with files put and cat.
I have first used safe files put to upload this and then safe cat <XOR-URL> to display its contents.
```
safe-cli/target/debug$ ./safe files put ../../to-upload/ -r
FilesContainer created at: "safe://hbywy5f3m6ei4fem9ap8pxc3a5e7gqujttjbmo45ty5c7itkjuudiaqj5w"
+  ../../to-upload/content.txt   safe://hoqkustgsouyaga1gj5cxnwrx6hag9x1wsd4bkero9xh4gnm8tpw5h 
+  ../../to-upload/file1.local   safe://hoxqae8rrzjknx1egn8ce7o335m5t4begonb4sfj7qkci6s6ki5b66 
+  ../../to-upload/image.png     safe://hoq9jah569zm3c1h6xfpuqwkjqhi4rnmaki4ufpojkgz74jtbzanp8 
+  ../../to-upload/index.html    safe://hoxubgksyo1ssbuhdtkb8s1w8tgtyw6bndhunabbjxc69ncjhtxa1s 
+  ../../to-upload/testfile.txt  safe://hoxqmqi8cfb957jrpqgsxmibh5rp9gescacjkk3ikwemkkdiynj3we
```
```
safe-cli/target/debug$ ./safe cat safe://hoqkustgsouyaga1gj5cxnwrx6hag9x1wsd4bkero9xh4gnm8tpw5h
This is a test to create a text file with some content to work with files put and cat.
I have first used safe files put to upload this and then safe cat <XOR-URL> to display its contents.
```

**Comment by calumcraig** [comment]
Moving to done.
