### ISSUE TITLE
Cat cmd: support for retrieving a specific version of a content, plus user guide updates

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe-cli#56]
The user shall be able to retrieve a specific version of the content either when the URL specifies it, e.g. `safe://<NRS/XOR URL>?v=<version>`, or by providing it as an arg in the CLI, e.g. `$ safe cat safe://<NRS/XOR URL> --version <version>`

**Comment by calumcraig** [comment]
After some discussion with the developers, clarified that this functionality
> by providing it as an arg in the CLI, e.g. $ safe cat safe://<NRS/XOR URL> --version <version>
is not to be implemented as the version is an integral part of the url, whether XOR or NRS. Reference to it is being  removed from the cli via issue #196 .

**Comment by calumcraig** [comment]
To test:
1. Create a local folder with contents.
2. Upload to (mock) network.
3. Make changes locally.
4. Files sync to create new version of filescontainer.
5. repeat 3 and 4.

Create local content and upload:
```
> ./safe files put testfolder1/ -r
FilesContainer created at: "safe://hnyynyz71admd7cu5b4xg4kstoqj3mng7dmb6dynmgspbpj8xatts96axobnc"
+  testfolder1/image1.png   safe://hbyyyynmimtuwcq4kbttgt14pbdk3amf7wr9a1cah8ounx953o1zx4gxoj 
+  testfolder1/index1.html  safe://hbyyyynmimtuwcq4kbttgt14pbdk3amf7wr9a1cah8ounx953o1zx4gxoj 
+  testfolder1/text1.txt    safe://hbyyyynmimtuwcq4kbttgt14pbdk3amf7wr9a1cah8ounx953o1zx4gxoj 
```
Make changes locally and sync a few times to create versions of the filescontainer:
```
> ./safe files sync testfolder1 safe://testfolder1 -r -d
FilesContainer synced up (version 1): "safe://testfolder1"
-  /image1.png                       safe://hbyyyynmimtuwcq4kbttgt14pbdk3amf7wr9a1cah8ounx953o1zx4gxoj 
-  /index1.html                      safe://hbyyyynmimtuwcq4kbttgt14pbdk3amf7wr9a1cah8ounx953o1zx4gxoj 
-  /text1.txt                        safe://hbyyyynmimtuwcq4kbttgt14pbdk3amf7wr9a1cah8ounx953o1zx4gxoj 
+  testfolder1/index1.html           safe://hbyyyynmimtuwcq4kbttgt14pbdk3amf7wr9a1cah8ounx953o1zx4gxoj 
+  testfolder1/newfileforthewin.txt  safe://hbyyyydj99a5hm68szc3ehnt4swbo7caziod9w53b5j87efsykjqyxoo4k 
+  testfolder1/text1.txt             safe://hbyyyyd8cjdrstr6exixdc9iw8ogajkd99tqj4b6eqkpe7z5puw3oyoqki 
```
```
> ./safe files sync testfolder1 safe://testfolder1 -r -d
FilesContainer synced up (version 2): "safe://testfolder1"
+  testfolder1/index.html  safe://hbyyyydj99a5hm68szc3ehnt4swbo7caziod9w53b5j87efsykjqyxoo4k 
*  testfolder1/text1.txt   safe://hbyyyydocpewkywr69gf3spmgc5pktxrd3qscg3pjgmwcishuw8d3dcm8b 
```
```
> ./safe files sync testfolder1 safe://testfolder1 -r -d
FilesContainer synced up (version 3): "safe://testfolder1"
+  testfolder1/neimagefile.jpg  safe://hbyyyydj99a5hm68szc3ehnt4swbo7caziod9w53b5j87efsykjqyxoo4k 
*  testfolder1/text1.txt        safe://hbyyyydmzawagmfniwbioh4sae486f7t3wprm6egkxybf3ayjf3pqa5kqo 
```
```
> ./safe files sync testfolder1 safe://testfolder1 -r -d
FilesContainer synced up (version 4): "safe://testfolder1"
-  /testfolder1/neimagefile.jpg  safe://hbyyyydj99a5hm68szc3ehnt4swbo7caziod9w53b5j87efsykjqyxoo4k 
+  testfolder1/newindex.html     safe://hbyyyydj99a5hm68szc3ehnt4swbo7caziod9w53b5j87efsykjqyxoo4k 
*  testfolder1/text1.txt         safe://hbyyyydh671d3d44m5x1n6muf3hsyycs9wo8k8am7ycibdxhzx5695mizh 
```

**Comment by calumcraig** [comment]
`cat` the various versions using `safe cat <xor_url>?v=version`:
```
$ ./safe cat safe://hnyynyz71admd7cu5b4xg4kstoqj3mng7dmb6dynmgspbpj8xatts96axobnc?v=0Files of FilesContainer (version 0) at "safe://hnyynyz71admd7cu5b4xg4kstoqj3mng7dmb6dynmgspbpj8xatts96axobnc?v=0":
+--------------+--------+----------------------+----------------------+-------------------------------------------------------------------+
| Name         | Size   | Created              | Modified             | Link                                                              |
+--------------+--------+----------------------+----------------------+-------------------------------------------------------------------+
| /image1.png  | 102400 | 2019-08-07T13:09:03Z | 2019-08-07T13:09:03Z | safe://hbyyyynmimtuwcq4kbttgt14pbdk3amf7wr9a1cah8ounx953o1zx4gxoj |
+--------------+--------+----------------------+----------------------+-------------------------------------------------------------------+
| /index1.html | 102400 | 2019-08-07T13:09:03Z | 2019-08-07T13:09:03Z | safe://hbyyyynmimtuwcq4kbttgt14pbdk3amf7wr9a1cah8ounx953o1zx4gxoj |
+--------------+--------+----------------------+----------------------+-------------------------------------------------------------------+
| /text1.txt   | 102400 | 2019-08-07T13:09:03Z | 2019-08-07T13:09:03Z | safe://hbyyyynmimtuwcq4kbttgt14pbdk3amf7wr9a1cah8ounx953o1zx4gxoj |
+--------------+--------+----------------------+----------------------+-------------------------------------------------------------------+
```
$ ./safe cat safe://hnyynyz71admd7cu5b4xg4kstoqj3mng7dmb6dynmgspbpj8xatts96axobnc?v=1Files of FilesContainer (version 1) at "safe://hnyynyz71admd7cu5b4xg4kstoqj3mng7dmb6dynmgspbpj8xatts96axobnc?v=1":
+-----------------------------------+--------+----------------------+----------------------+-------------------------------------------------------------------+
| Name                              | Size   | Created              | Modified             | Link                                                              |
+-----------------------------------+--------+----------------------+----------------------+-------------------------------------------------------------------+
| /testfolder1/index1.html          | 102400 | 2019-08-07T13:36:59Z | 2019-08-07T13:36:59Z | safe://hbyyyynmimtuwcq4kbttgt14pbdk3amf7wr9a1cah8ounx953o1zx4gxoj |
+-----------------------------------+--------+----------------------+----------------------+-------------------------------------------------------------------+
| /testfolder1/newfileforthewin.txt | 0      | 2019-08-07T13:36:59Z | 2019-08-07T13:36:59Z | safe://hbyyyydj99a5hm68szc3ehnt4swbo7caziod9w53b5j87efsykjqyxoo4k |
+-----------------------------------+--------+----------------------+----------------------+-------------------------------------------------------------------+
| /testfolder1/text1.txt            | 102474 | 2019-08-07T13:36:59Z | 2019-08-07T13:36:59Z | safe://hbyyyyd8cjdrstr6exixdc9iw8ogajkd99tqj4b6eqkpe7z5puw3oyoqki |
+-----------------------------------+--------+----------------------+----------------------+-------------------------------------------------------------------+
```
```
$ ./safe cat safe://hnyynyz71admd7cu5b4xg4kstoqj3mng7dmb6dynmgspbpj8xatts96axobnc?v=2Files of FilesContainer (version 2) at "safe://hnyynyz71admd7cu5b4xg4kstoqj3mng7dmb6dynmgspbpj8xatts96axobnc?v=2":
+-----------------------------------+--------+----------------------+----------------------+-------------------------------------------------------------------+
| Name                              | Size   | Created              | Modified             | Link                                                              |
+-----------------------------------+--------+----------------------+----------------------+-------------------------------------------------------------------+
| /testfolder1/index.html           | 0      | 2019-08-07T13:38:02Z | 2019-08-07T13:38:02Z | safe://hbyyyydj99a5hm68szc3ehnt4swbo7caziod9w53b5j87efsykjqyxoo4k |
+-----------------------------------+--------+----------------------+----------------------+-------------------------------------------------------------------+
| /testfolder1/index1.html          | 102400 | 2019-08-07T13:36:59Z | 2019-08-07T13:36:59Z | safe://hbyyyynmimtuwcq4kbttgt14pbdk3amf7wr9a1cah8ounx953o1zx4gxoj |
+-----------------------------------+--------+----------------------+----------------------+-------------------------------------------------------------------+
| /testfolder1/newfileforthewin.txt | 0      | 2019-08-07T13:36:59Z | 2019-08-07T13:36:59Z | safe://hbyyyydj99a5hm68szc3ehnt4swbo7caziod9w53b5j87efsykjqyxoo4k |
+-----------------------------------+--------+----------------------+----------------------+-------------------------------------------------------------------+
| /testfolder1/text1.txt            | 102515 | 2019-08-07T13:36:59Z | 2019-08-07T13:38:02Z | safe://hbyyyydocpewkywr69gf3spmgc5pktxrd3qscg3pjgmwcishuw8d3dcm8b |
+-----------------------------------+--------+----------------------+----------------------+-------------------------------------------------------------------+
```
```
$ ./safe cat safe://hnyynyz71admd7cu5b4xg4kstoqj3mng7dmb6dynmgspbpj8xatts96axobnc?v=3Files of FilesContainer (version 3) at "safe://hnyynyz71admd7cu5b4xg4kstoqj3mng7dmb6dynmgspbpj8xatts96axobnc?v=3":
+-----------------------------------+--------+----------------------+----------------------+-------------------------------------------------------------------+
| Name                              | Size   | Created              | Modified             | Link                                                              |
+-----------------------------------+--------+----------------------+----------------------+-------------------------------------------------------------------+
| /testfolder1/index.html           | 0      | 2019-08-07T13:38:02Z | 2019-08-07T13:38:02Z | safe://hbyyyydj99a5hm68szc3ehnt4swbo7caziod9w53b5j87efsykjqyxoo4k |
+-----------------------------------+--------+----------------------+----------------------+-------------------------------------------------------------------+
| /testfolder1/index1.html          | 102400 | 2019-08-07T13:36:59Z | 2019-08-07T13:36:59Z | safe://hbyyyynmimtuwcq4kbttgt14pbdk3amf7wr9a1cah8ounx953o1zx4gxoj |
+-----------------------------------+--------+----------------------+----------------------+-------------------------------------------------------------------+
| /testfolder1/neimagefile.jpg      | 0      | 2019-08-07T13:44:24Z | 2019-08-07T13:44:24Z | safe://hbyyyydj99a5hm68szc3ehnt4swbo7caziod9w53b5j87efsykjqyxoo4k |
+-----------------------------------+--------+----------------------+----------------------+-------------------------------------------------------------------+
| /testfolder1/newfileforthewin.txt | 0      | 2019-08-07T13:36:59Z | 2019-08-07T13:36:59Z | safe://hbyyyydj99a5hm68szc3ehnt4swbo7caziod9w53b5j87efsykjqyxoo4k |
+-----------------------------------+--------+----------------------+----------------------+-------------------------------------------------------------------+
| /testfolder1/text1.txt            | 102559 | 2019-08-07T13:36:59Z | 2019-08-07T13:44:24Z | safe://hbyyyydmzawagmfniwbioh4sae486f7t3wprm6egkxybf3ayjf3pqa5kqo |
+-----------------------------------+--------+----------------------+----------------------+-------------------------------------------------------------------+
```
```
$ ./safe cat safe://hnyynyz71admd7cu5b4xg4kstoqj3mng7dmb6dynmgspbpj8xatts96axobnc?v=4Files of FilesContainer (version 4) at "safe://hnyynyz71admd7cu5b4xg4kstoqj3mng7dmb6dynmgspbpj8xatts96axobnc?v=4":
+-----------------------------------+--------+----------------------+----------------------+-------------------------------------------------------------------+
| Name                              | Size   | Created              | Modified             | Link                                                              |
+-----------------------------------+--------+----------------------+----------------------+-------------------------------------------------------------------+
| /testfolder1/index.html           | 0      | 2019-08-07T13:38:02Z | 2019-08-07T13:38:02Z | safe://hbyyyydj99a5hm68szc3ehnt4swbo7caziod9w53b5j87efsykjqyxoo4k |
+-----------------------------------+--------+----------------------+----------------------+-------------------------------------------------------------------+
| /testfolder1/index1.html          | 102400 | 2019-08-07T13:36:59Z | 2019-08-07T13:36:59Z | safe://hbyyyynmimtuwcq4kbttgt14pbdk3amf7wr9a1cah8ounx953o1zx4gxoj |
+-----------------------------------+--------+----------------------+----------------------+-------------------------------------------------------------------+
| /testfolder1/newfileforthewin.txt | 0      | 2019-08-07T13:36:59Z | 2019-08-07T13:36:59Z | safe://hbyyyydj99a5hm68szc3ehnt4swbo7caziod9w53b5j87efsykjqyxoo4k |
+-----------------------------------+--------+----------------------+----------------------+-------------------------------------------------------------------+
| /testfolder1/newindex.html        | 0      | 2019-08-07T13:53:17Z | 2019-08-07T13:53:17Z | safe://hbyyyydj99a5hm68szc3ehnt4swbo7caziod9w53b5j87efsykjqyxoo4k |
+-----------------------------------+--------+----------------------+----------------------+-------------------------------------------------------------------+
| /testfolder1/text1.txt            | 102560 | 2019-08-07T13:36:59Z | 2019-08-07T13:53:17Z | safe://hbyyyydh671d3d44m5x1n6muf3hsyycs9wo8k8am7ycibdxhzx5695mizh |
+-----------------------------------+--------+----------------------+----------------------+-------------------------------------------------------------------+
```

**Comment by calumcraig** [comment]
Note (according to functionality as it currently exists), if we link an nrsurl to the filecontainer above, `safe cat <nrs_url>?=version` will **not** show the above versioning as version applied to the <nrs_url> shows the versions of the nrsurl, not its linked xorurl. To see the versions of the filescontainer we must use `<xor_url>?v=version`.

**Comment by calumcraig** [comment]
Just doing some further testing on this using a real (shared) vault before moving it to done.

Using the steps above, have created three versions of a filescontainer on the vault.
```
> ./safe files put newtestdata/ -r
FilesContainer created at: "safe://hnyynywzyoen4gxbjxiud531aryqjdnkgiru9oyym4zdf6cwxpqtcry9fqbnc"
+  newtestdata/01. What and Why Is World History.mp3  safe://hbyyyynssj7nwio8fu3yrafrihsrcxgkf4spzwk1cisyhyyac93g5nnj7x 
+  newtestdata/gab.png                                safe://hbyyyyna7tuq8kkhwtufr7ixjhq9dr96tysx5x7q7ya1pniwff79x1zm6z 
+  newtestdata/safe-network-icon-black.eps            safe://hbyyyyn9f5d6j8akm4ad54azacwp46pyefpohxj7aux7ewk8mhpt9uudqp 
+  newtestdata/safe-network-icon-black.png            safe://hbyyyydpwsrkkbi3pezfd4ib3sqr36xkauzfokf97mayofmwodtak9pepo 
+  newtestdata/safe-network-logo-black.svg            safe://hbyyyyn7eykrtf9gcysyc4d8b39rxg85ud36udfrzgf7ygy4z91qbx4fp7 
+  newtestdata/safenetworklogo.jpeg                   safe://hbyyyynnekr9afjjowihjydacjwpd818kbq9sxtt6patyftgy79sg4xka1 
+  newtestdata/test.png                               safe://hbyyyyn3zazdq4o45igsg8o4qhg6gow518ocfwuik65gnby43awc7zsg1u 
+  newtestdata/test2.jpg                              safe://hbyyyyny377qy6iwf9wxsj4otct8rt43sopgrpbyixcmmjdjpbuk4uu5f6 
+  newtestdata/version.txt                            safe://hbyyyyd6ts3ykn6e18pesdesbhprefedstynzcd38j55euqcudragncz9f 
```
Made some local changes and `files sync` each time to increment the filescontainer version.
```
> ./safe files sync newtestdata/ safe://hnyynywzyoen4gxbjxiud531aryqjdnkgiru9oyym4zdf6cwxpqtcry9fqbnc
FilesContainer synced up (version 1): "safe://hnyynywzyoen4gxbjxiud531aryqjdnkgiru9oyym4zdf6cwxpqtcry9fqbnc?v=1"
+  newtestdata/newtextfile.txt  safe://hbyyyydyg7ke4ryy4ibyndhhhpth7exqs7qowsydr8unu4ru75tcuswem7 
*  newtestdata/version.txt      safe://hbyyyynbbdt87pdpsfh3urmebn9tk947n9kteb6yw4tirf6f7uatqcjocz 
```
> ./safe files sync newtestdata/ safe://hnyynywzyoen4gxbjxiud531aryqjdnkgiru9oyym4zdf6cwxpqtcry9fqbnc -r -d 
FilesContainer synced up (version 2): "safe://hnyynywzyoen4gxbjxiud531aryqjdnkgiru9oyym4zdf6cwxpqtcry9fqbnc?v=2"
-  /safe-network-icon-black.eps    safe://hbyyyyn9f5d6j8akm4ad54azacwp46pyefpohxj7aux7ewk8mhpt9uudqp 
-  /test.png                       safe://hbyyyyn3zazdq4o45igsg8o4qhg6gow518ocfwuik65gnby43awc7zsg1u 
+  newtestdata/anothernewfile.txt  safe://hbyyyydj99a5hm68szc3ehnt4swbo7caziod9w53b5j87efsykjqyxoo4k 
*  newtestdata/version.txt         safe://hbyyyyd5wiht9dfos3j141k3pa7dwpoduaodksuo199niiwx9rcqy8m3b5 
```
Can now `cat` specific versions of the filescontainer itself or individual files:
```
> ./safe cat "safe://hnyynywzyoen4gxbjxiud531aryqjdnkgiru9oyym4zdf6cwxpqtcry9fqbnc?v=0"
Files of FilesContainer (version 0) at "safe://hnyynywzyoen4gxbjxiud531aryqjdnkgiru9oyym4zdf6cwxpqtcry9fqbnc?v=0":
+----------------------------------------+----------+----------------------+----------------------+-------------------------------------------------------------------+
| Name                                   | Size     | Created              | Modified             | Link                                                              |
+----------------------------------------+----------+----------------------+----------------------+-------------------------------------------------------------------+
| /01. What and Why Is World History.mp3 | 24904831 | 2019-09-05T09:14:57Z | 2019-09-05T09:14:57Z | safe://hbyyyynssj7nwio8fu3yrafrihsrcxgkf4spzwk1cisyhyyac93g5nnj7x |
+----------------------------------------+----------+----------------------+----------------------+-------------------------------------------------------------------+
| /gab.png                               | 269550   | 2019-09-05T09:14:57Z | 2019-09-05T09:14:57Z | safe://hbyyyyna7tuq8kkhwtufr7ixjhq9dr96tysx5x7q7ya1pniwff79x1zm6z |
+----------------------------------------+----------+----------------------+----------------------+-------------------------------------------------------------------+
| /safe-network-icon-black.eps           | 5151302  | 2019-09-05T09:14:57Z | 2019-09-05T09:14:57Z | safe://hbyyyyn9f5d6j8akm4ad54azacwp46pyefpohxj7aux7ewk8mhpt9uudqp |
+----------------------------------------+----------+----------------------+----------------------+-------------------------------------------------------------------+
| /safe-network-icon-black.png           | 24063    | 2019-09-05T09:14:57Z | 2019-09-05T09:14:57Z | safe://hbyyyydpwsrkkbi3pezfd4ib3sqr36xkauzfokf97mayofmwodtak9pepo |
+----------------------------------------+----------+----------------------+----------------------+-------------------------------------------------------------------+
| /safe-network-logo-black.svg           | 4078     | 2019-09-05T09:14:57Z | 2019-09-05T09:14:57Z | safe://hbyyyyn7eykrtf9gcysyc4d8b39rxg85ud36udfrzgf7ygy4z91qbx4fp7 |
+----------------------------------------+----------+----------------------+----------------------+-------------------------------------------------------------------+
| /safenetworklogo.jpeg                  | 6161     | 2019-09-05T09:14:57Z | 2019-09-05T09:14:57Z | safe://hbyyyynnekr9afjjowihjydacjwpd818kbq9sxtt6patyftgy79sg4xka1 |
+----------------------------------------+----------+----------------------+----------------------+-------------------------------------------------------------------+
| /test.png                              | 3854     | 2019-09-05T09:14:57Z | 2019-09-05T09:14:57Z | safe://hbyyyyn3zazdq4o45igsg8o4qhg6gow518ocfwuik65gnby43awc7zsg1u |
+----------------------------------------+----------+----------------------+----------------------+-------------------------------------------------------------------+
| /test2.jpg                             | 51756    | 2019-09-05T09:14:57Z | 2019-09-05T09:14:57Z | safe://hbyyyyny377qy6iwf9wxsj4otct8rt43sopgrpbyixcmmjdjpbuk4uu5f6 |
+----------------------------------------+----------+----------------------+----------------------+-------------------------------------------------------------------+
| /version.txt                           | 44       | 2019-09-05T09:14:57Z | 2019-09-05T09:14:57Z | safe://hbyyyyd6ts3ykn6e18pesdesbhprefedstynzcd38j55euqcudragncz9f |
+----------------------------------------+----------+----------------------+----------------------+-----------------------------------------------------------
```
```
> ./safe cat "safe://hnyynywzyoen4gxbjxiud531aryqjdnkgiru9oyym4zdf6cwxpqtcry9fqbnc?v=1"
Files of FilesContainer (version 1) at "safe://hnyynywzyoen4gxbjxiud531aryqjdnkgiru9oyym4zdf6cwxpqtcry9fqbnc?v=1":
+----------------------------------------+----------+----------------------+----------------------+-------------------------------------------------------------------+
| Name                                   | Size     | Created              | Modified             | Link                                                              |
+----------------------------------------+----------+----------------------+----------------------+-------------------------------------------------------------------+
| /01. What and Why Is World History.mp3 | 24904831 | 2019-09-05T09:14:57Z | 2019-09-05T09:14:57Z | safe://hbyyyynssj7nwio8fu3yrafrihsrcxgkf4spzwk1cisyhyyac93g5nnj7x |
+----------------------------------------+----------+----------------------+----------------------+-------------------------------------------------------------------+
| /gab.png                               | 269550   | 2019-09-05T09:14:57Z | 2019-09-05T09:14:57Z | safe://hbyyyyna7tuq8kkhwtufr7ixjhq9dr96tysx5x7q7ya1pniwff79x1zm6z |
+----------------------------------------+----------+----------------------+----------------------+-------------------------------------------------------------------+
| /newtextfile.txt                       | 51       | 2019-09-05T09:33:24Z | 2019-09-05T09:33:24Z | safe://hbyyyydyg7ke4ryy4ibyndhhhpth7exqs7qowsydr8unu4ru75tcuswem7 |
+----------------------------------------+----------+----------------------+----------------------+-------------------------------------------------------------------+
| /safe-network-icon-black.eps           | 5151302  | 2019-09-05T09:14:57Z | 2019-09-05T09:14:57Z | safe://hbyyyyn9f5d6j8akm4ad54azacwp46pyefpohxj7aux7ewk8mhpt9uudqp |
+----------------------------------------+----------+----------------------+----------------------+-------------------------------------------------------------------+
| /safe-network-icon-black.png           | 24063    | 2019-09-05T09:14:57Z | 2019-09-05T09:14:57Z | safe://hbyyyydpwsrkkbi3pezfd4ib3sqr36xkauzfokf97mayofmwodtak9pepo |
+----------------------------------------+----------+----------------------+----------------------+-------------------------------------------------------------------+
| /safe-network-logo-black.svg           | 4078     | 2019-09-05T09:14:57Z | 2019-09-05T09:14:57Z | safe://hbyyyyn7eykrtf9gcysyc4d8b39rxg85ud36udfrzgf7ygy4z91qbx4fp7 |
+----------------------------------------+----------+----------------------+----------------------+-------------------------------------------------------------------+
| /safenetworklogo.jpeg                  | 6161     | 2019-09-05T09:14:57Z | 2019-09-05T09:14:57Z | safe://hbyyyynnekr9afjjowihjydacjwpd818kbq9sxtt6patyftgy79sg4xka1 |
+----------------------------------------+----------+----------------------+----------------------+-------------------------------------------------------------------+
| /test.png                              | 3854     | 2019-09-05T09:14:57Z | 2019-09-05T09:14:57Z | safe://hbyyyyn3zazdq4o45igsg8o4qhg6gow518ocfwuik65gnby43awc7zsg1u |
+----------------------------------------+----------+----------------------+----------------------+-------------------------------------------------------------------+
| /test2.jpg                             | 51756    | 2019-09-05T09:14:57Z | 2019-09-05T09:14:57Z | safe://hbyyyyny377qy6iwf9wxsj4otct8rt43sopgrpbyixcmmjdjpbuk4uu5f6 |
+----------------------------------------+----------+----------------------+----------------------+-------------------------------------------------------------------+
| /version.txt                           | 145      | 2019-09-05T09:14:57Z | 2019-09-05T09:33:24Z | safe://hbyyyynbbdt87pdpsfh3urmebn9tk947n9kteb6yw4tirf6f7uatqcjocz |
+----------------------------------------+----------+----------------------+----------------------+-----------------------------------------------------------
```
```
> ./safe cat "safe://hnyynywzyoen4gxbjxiud531aryqjdnkgiru9oyym4zdf6cwxpqtcry9fqbnc?v=2"
Files of FilesContainer (version 2) at "safe://hnyynywzyoen4gxbjxiud531aryqjdnkgiru9oyym4zdf6cwxpqtcry9fqbnc?v=2":
+----------------------------------------+----------+----------------------+----------------------+-------------------------------------------------------------------+
| Name                                   | Size     | Created              | Modified             | Link                                                              |
+----------------------------------------+----------+----------------------+----------------------+-------------------------------------------------------------------+
| /01. What and Why Is World History.mp3 | 24904831 | 2019-09-05T09:14:57Z | 2019-09-05T09:14:57Z | safe://hbyyyynssj7nwio8fu3yrafrihsrcxgkf4spzwk1cisyhyyac93g5nnj7x |
+----------------------------------------+----------+----------------------+----------------------+-------------------------------------------------------------------+
| /anothernewfile.txt                    | 0        | 2019-09-05T09:34:57Z | 2019-09-05T09:34:57Z | safe://hbyyyydj99a5hm68szc3ehnt4swbo7caziod9w53b5j87efsykjqyxoo4k |
+----------------------------------------+----------+----------------------+----------------------+-------------------------------------------------------------------+
| /gab.png                               | 269550   | 2019-09-05T09:14:57Z | 2019-09-05T09:14:57Z | safe://hbyyyyna7tuq8kkhwtufr7ixjhq9dr96tysx5x7q7ya1pniwff79x1zm6z |
+----------------------------------------+----------+----------------------+----------------------+-------------------------------------------------------------------+
| /newtextfile.txt                       | 51       | 2019-09-05T09:33:24Z | 2019-09-05T09:33:24Z | safe://hbyyyydyg7ke4ryy4ibyndhhhpth7exqs7qowsydr8unu4ru75tcuswem7 |
+----------------------------------------+----------+----------------------+----------------------+-------------------------------------------------------------------+
| /safe-network-icon-black.png           | 24063    | 2019-09-05T09:14:57Z | 2019-09-05T09:14:57Z | safe://hbyyyydpwsrkkbi3pezfd4ib3sqr36xkauzfokf97mayofmwodtak9pepo |
+----------------------------------------+----------+----------------------+----------------------+-------------------------------------------------------------------+
| /safe-network-logo-black.svg           | 4078     | 2019-09-05T09:14:57Z | 2019-09-05T09:14:57Z | safe://hbyyyyn7eykrtf9gcysyc4d8b39rxg85ud36udfrzgf7ygy4z91qbx4fp7 |
+----------------------------------------+----------+----------------------+----------------------+-------------------------------------------------------------------+
| /safenetworklogo.jpeg                  | 6161     | 2019-09-05T09:14:57Z | 2019-09-05T09:14:57Z | safe://hbyyyynnekr9afjjowihjydacjwpd818kbq9sxtt6patyftgy79sg4xka1 |
+----------------------------------------+----------+----------------------+----------------------+-------------------------------------------------------------------+
| /test2.jpg                             | 51756    | 2019-09-05T09:14:57Z | 2019-09-05T09:14:57Z | safe://hbyyyyny377qy6iwf9wxsj4otct8rt43sopgrpbyixcmmjdjpbuk4uu5f6 |
+----------------------------------------+----------+----------------------+----------------------+-------------------------------------------------------------------+
| /version.txt                           | 174      | 2019-09-05T09:14:57Z | 2019-09-05T09:34:57Z | safe://hbyyyyd5wiht9dfos3j141k3pa7dwpoduaodksuo199niiwx9rcqy8m3b5 |
+----------------------------------------+----------+----------------------+----------------------+-----------------------------------------------------------
```

**Comment by calumcraig** [comment]
```
> ./safe cat "safe://hnyynywzyoen4gxbjxiud531aryqjdnkgiru9oyym4zdf6cwxpqtcry9fqbnc/version.txt?v=0"
This is version 0 - no edits / updates yet.
```
```
> ./safe cat "safe://hnyynywzyoen4gxbjxiud531aryqjdnkgiru9oyym4zdf6cwxpqtcry9fqbnc/version.txt?v=1"
This is version 0 - no edits / updates yet.

This now version 1. Have made some changes to the locak testdata and will sync with the vault data.
```
```
> ./safe cat "safe://hnyynywzyoen4gxbjxiud531aryqjdnkgiru9oyym4zdf6cwxpqtcry9fqbnc/version.txt?v=2"
This is version 0 - no edits / updates yet.

This now version 1. Have made some changes to the locak testdata and will sync with the vault data.

And, now we have version 2!
```

**Comment by calumcraig** [comment]
Moving this to done.
