### ISSUE TITLE
Files put cmd: files put subcommand to upload entire Published folders

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe-cli#57]
This makes use of only Published-AppendOnlyData and Published-ImmutableData types.

A `FilesContainer` (non-RDF data representation at this stage) shall be created as a Published-AppendOnlyData, and all files from the source folder shall be uploaded as Published-ImmutableData files on the network, linking them from the FilesContainer flattening the path and using their XOR-URLs.

```
$ safe files put --source ./to-upload/ --recursive --pretty
All files and subfolders of './to_upload/' folder were uploaded at: "safe://<FilesContainer XOR-URL>"
Links created in the FilesContainer:
+ index.html             safe://<'index.html' file XOR-URL>
+ myfolder/notes.txt     safe://<'notes.txt' file XOR-URL>
+ img.jpeg               safe://<'img.jpeg' file XOR-URL>
```

A special entry in the FilesContainer can be added as metadata trying to mimic the RDF self-description feature, e.g. key = "_container_type", value = "safe:FilesContainer", since this will be needed for the `$ safe cat` command to render accordingly.

**Comment by calumcraig** [comment]
`safe files put --recursive` command works to upload the entire contents of a specified folder:

```
$ ./safe files put ../to-upload/ -r
FilesContainer created at: "safe://hbyzpg7hfw8j5acj7shw5xaba5ok9cfzwbefp6renwjuk8me6pbytmcj5w"
+  ../to-upload/file1.local  safe://hoxzb3ykxunymtynws9mrqidj7gipbriajhwkjs78hoge1peh7um9s 
+  ../to-upload/file2.info   safe://hoqd571m1jz7zp9rq1aaszawd5x6i6mj6qbbms91n4s1oait6b11wo 
+  ../to-upload/file3.html   safe://hoqf347wu417ewrnfu6rd4gw1btm6xcjgzh3fstzkaeaaqxqc9pgfp
```

**Comment by calumcraig** [comment]
QA verified, moving to done.
