### ISSUE TITLE
Files sync subcommand

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe-cli#58]
E.g.:
```
$ safe files sync --source ./to-upload/ --target safe://<FilesContainer XOR-URL> --recursive --pretty
+ index.html             safe://<'index.html' file XOR-URL>
+ myfolder/notes.txt     safe://<'notes.txt' file XOR-URL>
* img.jpeg               safe://<'img.jpeg' file XOR-URL>
```

The `+` and `*` signs mean that the files were added and updated respectively.

**Comment by wardbr** [comment]
Will 'safe files sync ./to-upload/ safe://<FilesContainer XOR-URL> --recursive --pretty' also be possible (without the --source and the --target)? That seems more logical to me.

**Comment by bochaco** [comment]
Yes probably @wardbr , @joshuef was proposing we use positional args as you also sugest here in all commands, and we agreed to go that path as much as possible, although based on the first version we had with `wallet insert` args I think we should try to stick to max two positional args and the rest to make them explicit with `--<arg name>` as it becomes confusing I think.

**Comment by wardbr** [comment]
It depends on the situation I think, a file/dir from <src> to <dst> is a well known often occurring use of 2 positional args. 1 use case of more than 2 I know out of my head: 'scp <src_1> [<src_2>] ... [<src_n>] <dst>'. But that is less often used and I also think for new/not that familiar sub cmd args more than 2 positional args could be confusing. Or are you already counting e.g. 'safe **files sync** ...' as 2 positional args? _--> 'git clone <repository> [<directory>]' seems to be no problem._

**Comment by bochaco** [comment]
No, `files sync` are the command and subcommand, so we are talking about the same thing here.

**Comment by bochaco** [comment]
An example output using `files put` and `files sync` with the PR that implemented this feature:
```shell
$ safe files put ./tests/testfolder -r
FilesContainer created at: "safe://hbyw8kkqr3tcwfqiiqh4qeaehzr1e9boiuyfw5bqqx1adyh9sawdhboj5w"
+  ./tests/testfolder/another.md              safe://hoxm5aps8my8he8cpgdqh8k5wuox5p7kzed6bsbajayc3gc8pgp36s
+  ./tests/testfolder/subfolder/subexists.md  safe://hoqc6etdwbx6s86u3bkxenos3rf7dtr51eqdt17smxsw7aejot81dc
+  ./tests/testfolder/test.md                 safe://hoxibhqth9awkjgi35sz73u35wyyscuht65m3ztrznb6thd5z8hepx

$ safe cat safe://hbyw8kkqr3tcwfqiiqh4qeaehzr1e9boiuyfw5bqqx1adyh9sawdhboj5w
Files of FilesContainer (version 1) at: "safe://hbyw8kkqr3tcwfqiiqh4qeaehzr1e9boiuyfw5bqqx1adyh9sawdhboj5w"
+-------------------------+------+----------------------+----------------------+---------------------------------------------------------------+
| Name                    | Size | Created              | Modified             | Link                                                          |
+-------------------------+------+----------------------+----------------------+---------------------------------------------------------------+
| /another.md             | 7    | 2019-07-04T06:01:13Z | 2019-07-04T06:01:13Z | safe://hoxm5aps8my8he8cpgdqh8k5wuox5p7kzed6bsbajayc3gc8pgp36s |
+-------------------------+------+----------------------+----------------------+---------------------------------------------------------------+
| /subfolder/subexists.md | 8    | 2019-07-04T06:01:13Z | 2019-07-04T06:01:13Z | safe://hoqc6etdwbx6s86u3bkxenos3rf7dtr51eqdt17smxsw7aejot81dc |
+-------------------------+------+----------------------+----------------------+---------------------------------------------------------------+
| /test.md                | 13   | 2019-07-04T06:01:13Z | 2019-07-04T06:01:13Z | safe://hoxibhqth9awkjgi35sz73u35wyyscuht65m3ztrznb6thd5z8hepx |
+-------------------------+------+----------------------+----------------------+---------------------------------------------------------------+

$ safe cat safe://hbyw8kkqr3tcwfqiiqh4qeaehzr1e9boiuyfw5bqqx1adyh9sawdhboj5w/another.md
exists

$ echo 'exists and updated!' > tests/testfolder/another.md
$ touch tests/testfolder/new.md
$ echo 'this is to be added' > tests/testfolder/new.md
$ rm tests/testfolder/test.md

$ safe files sync ./tests/testfolder -r --delete safe://hbyw8kkqr3tcwfqiiqh4qeaehzr1e9boiuyfw5bqqx1adyh9sawdhboj5w
FilesContainer synced up (version 2): "safe://hbyw8kkqr3tcwfqiiqh4qeaehzr1e9boiuyfw5bqqx1adyh9sawdhboj5w"
*  ./tests/testfolder/another.md  safe://hox6jstso13b7wzfkw1wbs3kwn9gpssudqunk6sw5yt3d6pnmaec53 
+  ./tests/testfolder/new.md      safe://hoxpdc8ywz18twkg7wboarj45hem3pq6ou6sati9i3dud68tzutw34
-  /test.md                       safe://hoxibhqth9awkjgi35sz73u35wyyscuht65m3ztrznb6thd5z8hepx

$ safe cat safe://hbyw8kkqr3tcwfqiiqh4qeaehzr1e9boiuyfw5bqqx1adyh9sawdhboj5w
Files of FilesContainer (version 2) at: "safe://hbyw8kkqr3tcwfqiiqh4qeaehzr1e9boiuyfw5bqqx1adyh9sawdhboj5w"
+-------------------------+------+----------------------+----------------------+---------------------------------------------------------------+
| Name                    | Size | Created              | Modified             | Link                                                          |
+-------------------------+------+----------------------+----------------------+---------------------------------------------------------------+
| /another.md             | 20   | 2019-07-04T06:01:13Z | 2019-07-04T06:03:29Z | safe://hox6jstso13b7wzfkw1wbs3kwn9gpssudqunk6sw5yt3d6pnmaec53 |
+-------------------------+------+----------------------+----------------------+---------------------------------------------------------------+
| /new.md                 | 20   | 2019-07-04T06:03:29Z | 2019-07-04T06:03:29Z | safe://hoxpdc8ywz18twkg7wboarj45hem3pq6ou6sati9i3dud68tzutw34 |
+-------------------------+------+----------------------+----------------------+---------------------------------------------------------------+
| /subfolder/subexists.md | 8    | 2019-07-04T06:01:13Z | 2019-07-04T06:01:13Z | safe://hoqc6etdwbx6s86u3bkxenos3rf7dtr51eqdt17smxsw7aejot81dc |
+-------------------------+------+----------------------+----------------------+---------------------------------------------------------------+

$ cargo run --features scl-mock -- cat safe://hbyw8kkqr3tcwfqiiqh4qeaehzr1e9boiuyfw5bqqx1adyh9sawdhboj5w/another.md
exists and updated!
```

**Comment by calumcraig** [comment]
To test the `sync` function:
1. Created a local `test-upload` folder with some contents:
```
test-upload-data$ ls -la
total 12
drwxr-xr-x  3 root  root  4096 Jul  5 14:42 .
drwxrwxr-x 10 calum calum 4096 Jul  5 13:53 ..
-rw-r--r--  1 root  root     0 Jul  5 13:55 file1.txt
-rw-r--r--  1 root  root     0 Jul  5 13:56 file2.html
-rw-r--r--  1 root  root     0 Jul  5 13:56 file3.png
drwxr-xr-x  2 root  root  4096 Jul  5 14:43 subfolder1
```
```
`subfolder` contains a file with content:
```
test-upload-data/subfolder1$ cat file1.txt 
Test data here.

safe-cli put, cat and sync are awesome!

```
Upload this folder to (mock) SAFE:
```
$ ./safe files put ../../test-upload-data/ -r
FilesContainer created at: "safe://hbyzrhhj5zpgih8iafr3rek87znkakrbnkjqgtiwn4pwiz83rtcqakaj5w"
+  ../../test-upload-data/file1.txt             safe://hoxbxa4g43365ua8ydcm837hfowhm1ng8amk7qsm119nauudk1ddtu 
+  ../../test-upload-data/file2.html            safe://hoxme9at7k7ubx7x4dpr4mr8634594mn498ykmuskz36ynzung4ft6 
+  ../../test-upload-data/file3.png             safe://hoqh73gs7e6g34fhkqkt1354pfcbb1d4hns9t5zah4uejx6q3ahhsu 
+  ../../test-upload-data/subfolder1/file1.txt  safe://hoqm11xfxf4jfxni1cm3hohtfma3z4h6hiqke9utxeghjmjxw6mfxo 
```
Then verify the upload:
```
$ ./safe cat safe://hbyzrhhj5zpgih8iafr3rek87znkakrbnkjqgtiwn4pwiz83rtcqakaj5w --info
Native data type: AppendOnlyData
Type tag: 10100
XOR name: 0xc9ce277769abc3d7052648851fb712b0a2044a4b8d1ad05a6d2b73e49163b0ac

Files of FilesContainer (version 1) at "safe://hbyzrhhj5zpgih8iafr3rek87znkakrbnkjqgtiwn4pwiz83rtcqakaj5w":
+-----------------------+------+----------------------+----------------------+---------------------------------------------------------------+
| Name                  | Size | Created              | Modified             | Link                                                          |
+-----------------------+------+----------------------+----------------------+---------------------------------------------------------------+
| /file1.txt            | 0    | 2019-07-05T13:44:41Z | 2019-07-05T13:44:41Z | safe://hoxbxa4g43365ua8ydcm837hfowhm1ng8amk7qsm119nauudk1ddtu |
+-----------------------+------+----------------------+----------------------+---------------------------------------------------------------+
| /file2.html           | 0    | 2019-07-05T13:44:41Z | 2019-07-05T13:44:41Z | safe://hoxme9at7k7ubx7x4dpr4mr8634594mn498ykmuskz36ynzung4ft6 |
+-----------------------+------+----------------------+----------------------+---------------------------------------------------------------+
| /file3.png            | 0    | 2019-07-05T13:44:41Z | 2019-07-05T13:44:41Z | safe://hoqh73gs7e6g34fhkqkt1354pfcbb1d4hns9t5zah4uejx6q3ahhsu |
+-----------------------+------+----------------------+----------------------+---------------------------------------------------------------+
| /subfolder1/file1.txt | 57   | 2019-07-05T13:44:41Z | 2019-07-05T13:44:41Z | safe://hoqm11xfxf4jfxni1cm3hohtfma3z4h6hiqke9utxeghjmjxw6mfxo |
+-----------------------+------+----------------------+----------------------+---------------------------------------------------------------+
```

**Comment by calumcraig** [comment]
2)
4. Make some modifications to the local `test-upload` folder:
- Add text to `file1.txt` (previously empty)
```
$ cat file1.txt 
This is new text to be synced to SAFE.

```
- Delete `file3.png`
- Add new file `file3.info`
```
test-upload-data$ ls -la
total 16
drwxr-xr-x  3 root  root  4096 Jul  5 15:29 .
drwxrwxr-x 10 calum calum 4096 Jul  5 13:53 ..
-rw-r--r--  1 root  root    39 Jul  5 15:27 file1.txt
-rw-r--r--  1 root  root     0 Jul  5 13:56 file2.html
-rw-r--r--  1 root  root     0 Jul  5 15:29 file3.info
drwxr-xr-x  2 root  root  4096 Jul  5 15:22 subfolder1

```
- Edit `subfolder/file1.txt`
```
test-upload-data/subfolder1$ cat file1.txt 
Test data here.

safe-cli put, cat and sync are still awesome and this is an edited update

```

**Comment by calumcraig** [comment]
3)
5. `sync` with previously uploaded folder:
```
$ ./safe files sync ../../test-upload-data/ safe://hbyzrhhj5zpgih8iafr3rek87znkakrbnkjqgtiwn4pwiz83rtcqakaj5w -r
FilesContainer synced up (version 2): "safe://hbyzrhhj5zpgih8iafr3rek87znkakrbnkjqgtiwn4pwiz83rtcqakaj5w"
*  ../../test-upload-data/file1.txt             safe://hoqzu4z8i31kz9u8f3ichkt7y3gi85t1ccagk6e71ob8b1yo9bk5on 
+  ../../test-upload-data/file3.info            safe://hoxrkh4ee8bcuwiegs7wun5tp7sw9deyn5eumkzkg7uu6wspj1p58u 
*  ../../test-upload-data/subfolder1/file1.txt  safe://hoqzg3mye78mmz6uru19hock98y5dkw5hxtty6bh9eo11u1gnaftik
```

**Comment by calumcraig** [comment]
6. Verify the files on SAFE are synced:
```
$ ./safe cat safe://hbyzrhhj5zpgih8iafr3rek87znkakrbnkjqgtiwn4pwiz83rtcqakaj5w --info
Native data type: AppendOnlyData
Type tag: 10100
XOR name: 0xc9ce277769abc3d7052648851fb712b0a2044a4b8d1ad05a6d2b73e49163b0ac

Files of FilesContainer (version 2) at "safe://hbyzrhhj5zpgih8iafr3rek87znkakrbnkjqgtiwn4pwiz83rtcqakaj5w":
+-----------------------+------+----------------------+----------------------+---------------------------------------------------------------+
| Name                  | Size | Created              | Modified             | Link                                                          |
+-----------------------+------+----------------------+----------------------+---------------------------------------------------------------+
| /file1.txt            | 39   | 2019-07-05T13:44:41Z | 2019-07-05T14:36:11Z | safe://hoqzu4z8i31kz9u8f3ichkt7y3gi85t1ccagk6e71ob8b1yo9bk5on |
+-----------------------+------+----------------------+----------------------+---------------------------------------------------------------+
| /file2.html           | 0    | 2019-07-05T13:44:41Z | 2019-07-05T13:44:41Z | safe://hoxme9at7k7ubx7x4dpr4mr8634594mn498ykmuskz36ynzung4ft6 |
+-----------------------+------+----------------------+----------------------+---------------------------------------------------------------+
| /file3.info           | 0    | 2019-07-05T14:36:11Z | 2019-07-05T14:36:11Z | safe://hoxrkh4ee8bcuwiegs7wun5tp7sw9deyn5eumkzkg7uu6wspj1p58u |
+-----------------------+------+----------------------+----------------------+---------------------------------------------------------------+
| /file3.png            | 0    | 2019-07-05T13:44:41Z | 2019-07-05T13:44:41Z | safe://hoqh73gs7e6g34fhkqkt1354pfcbb1d4hns9t5zah4uejx6q3ahhsu |
+-----------------------+------+----------------------+----------------------+---------------------------------------------------------------+
| /subfolder1/file1.txt | 91   | 2019-07-05T13:44:41Z | 2019-07-05T14:36:11Z | safe://hoqzg3mye78mmz6uru19hock98y5dkw5hxtty6bh9eo11u1gnaftik |
+-----------------------+------+----------------------+----------------------+---------------------------------------------------------------+
```

```
$ ./safe cat safe://hoqzu4z8i31kz9u8f3ichkt7y3gi85t1ccagk6e71ob8b1yo9bk5on
This is new text to be synced to SAFE.

```
```
$ ./safe cat safe://hoqzg3mye78mmz6uru19hock98y5dkw5hxtty6bh9eo11u1gnaftik
Test data here.

```

**Comment by calumcraig** [comment]
Note that file3.png is not removed until I pass the `--delete` flag:
```
$ ./safe files sync ../../test-upload-data/ safe://hbyzrhhj5zpgih8iafr3rek87znkakrbnkjqgtiwn4pwiz83rtcqakaj5w -r --delete
FilesContainer synced up (version 3): "safe://hbyzrhhj5zpgih8iafr3rek87znkakrbnkjqgtiwn4pwiz83rtcqakaj5w"
-  /file3.png  safe://hoqh73gs7e6g34fhkqkt1354pfcbb1d4hns9t5zah4uejx6q3ahhsu 
```
$ ./safe cat safe://hbyzrhhj5zpgih8iafr3rek87znkakrbnkjqgtiwn4pwiz83rtcqakaj5w --info
Native data type: AppendOnlyData
Type tag: 10100
XOR name: 0xc9ce277769abc3d7052648851fb712b0a2044a4b8d1ad05a6d2b73e49163b0ac

Files of FilesContainer (version 3) at "safe://hbyzrhhj5zpgih8iafr3rek87znkakrbnkjqgtiwn4pwiz83rtcqakaj5w":
+-----------------------+------+----------------------+----------------------+---------------------------------------------------------------+
| Name                  | Size | Created              | Modified             | Link                                                          |
+-----------------------+------+----------------------+----------------------+---------------------------------------------------------------+
| /file1.txt            | 39   | 2019-07-05T13:44:41Z | 2019-07-05T14:36:11Z | safe://hoqzu4z8i31kz9u8f3ichkt7y3gi85t1ccagk6e71ob8b1yo9bk5on |
+-----------------------+------+----------------------+----------------------+---------------------------------------------------------------+
| /file2.html           | 0    | 2019-07-05T13:44:41Z | 2019-07-05T13:44:41Z | safe://hoxme9at7k7ubx7x4dpr4mr8634594mn498ykmuskz36ynzung4ft6 |
+-----------------------+------+----------------------+----------------------+---------------------------------------------------------------+
| /file3.info           | 0    | 2019-07-05T14:36:11Z | 2019-07-05T14:36:11Z | safe://hoxrkh4ee8bcuwiegs7wun5tp7sw9deyn5eumkzkg7uu6wspj1p58u |
+-----------------------+------+----------------------+----------------------+---------------------------------------------------------------+
| /subfolder1/file1.txt | 91   | 2019-07-05T13:44:41Z | 2019-07-05T14:36:11Z | safe://hoqzg3mye78mmz6uru19hock98y5dkw5hxtty6bh9eo11u1gnaftik |
+-----------------------+------+----------------------+----------------------+---------------------------------------------------------------+
```

**Comment by bochaco** [comment]
nice tests!!!
