### ISSUE TITLE
NRS cmd: integration tests, and user guide updates

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe-cli#72]

**Comment by calumcraig** [comment]
[As discussed](https://maidsafe.slack.com/archives/CHJ1HPV29/p1564667765352900?thread_ts=1564667419.350000&cid=CHJ1HPV29), can we add a little more detail around the `nrs add` command, ie that it will update existing nrsurls as well as add new ones?

Suggestion:
> Furthermore, the `safe nrs add` command can be used to update subname after they have been added to a public name.
For example, if we have made changes to files mapped to the `profile.mywebsite` NRS subname name we created before, we can use `add` to update:
```
> ./safe nrs add profile.mywebsite --link safe://hnyynyw9ru4afkbfee5m4ca4jbho4f5bj6ynep5k1pioyge6dihfqyjfrnbnc
NRS Map updated (version 3): "safe://profile.hnyydyz7utb6npt9kg3aksgorfwmkphet8u8z3or4nsu8n3bj8yiep4a91bqh"
+  profile.mywebsite  safe://hnyynyw9ru4afkbfee5m4ca4jbho4f5bj6ynep5k1pioyge6dihfqyjfrnbnc 
```

**Comment by calumcraig** [comment]
Moving this back to In Progress for update to the documentation.

The `nrs` related commands have been tested elsewhere so that aspect of this issue is fine.

**Comment by calumcraig** [comment]
We can see the above suggestion has been implemented to give some guidance for `nrs add`, ie that it can be used to update existing nrsurls.

Will raise a pr to fix the formatting of the text but moving this issue to done as the content has been updated.
