### ISSUE TITLE
`test_wallet_transfer_no_default` unit test failing with feature `mock-network`

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe-cli#82]
When running unit tests against SCL mock-network one test (`test_wallet_transfer_no_default`) is failing due to a bug in SCL. We depend on a fix for issue https://github.com/maidsafe/safe_client_libs/issues/842

**Comment by calumcraig** [comment]
Just moving this to done as not really an applicable bug for QA https://maidsafe.slack.com/archives/CHJ1HPV29/p1564500522259900
