### ISSUE TITLE
Files sync: support --delete files found at target but not in source

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe-cli#91]
E.g.:
```
$ safe files sync --source ./other-to-upload/ --target safe://<XOR-URL> --recursive --delete --pretty
- index.html     
- myfolder/notes.txt
* img.jpeg               safe://<'img.jpeg' file XOR-URL>
```

The `-` and `*` signs mean that the files were removed and updated respectively.

**Comment by bochaco** [comment]
This was completed already also with PR #58

**Comment by calumcraig** [comment]
The `--delete` subfunction of `sync` was tested and results can be seen here: https://github.com/maidsafe/safe-cli/issues/120#issuecomment-509559674

**Comment by calumcraig** [comment]
QA verified, moving this to done.
