### ISSUE TITLE
Wallet Create/Insert Improvements

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe-cli#92]
The aim is to simplify things and improve UX, as these two are confusing.

## Wallet Create

Should also create a spendable balance (much as `wallet insert` will right now). A `key` _MAY_ be passed.

## Wallet Insert

_MUST_ have a key passed. No default creation should happen here.

**Comment by calumcraig** [comment]
When trying to `wallet insert` with only two arguments, it doesn't create a new key (as was previously the case when key was optional) but it doesn't handle the missing mandatory argument. I've raised a bug to cover this #115

**Comment by calumcraig** [comment]
`wallet create` is seen to work both when a `pk` is passed to it or not.

**Comment by calumcraig** [comment]
QA verified, moving this to done.
